# Generated by Django 5.2 on 2025-06-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mssv',
        ),
    ]
