# Generated by Django 5.2.2 on 2025-06-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0002_remove_customuser_mssv"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentattendance",
            unique_together={("student", "subject_date")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectstudent",
            unique_together={("subject", "student")},
        ),
    ]
